# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["flutterflow"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/"

      - name: Deploy to Pages repository
        run: |
          # Clona el repo de Pages usando tu ACCESS_TOKEN
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/dgarsau/dgarsau.github.io pages-repo

          # Borra contenido viejo
          rm -rf pages-repo/*

          # Copia la nueva build
          cp -r build/web/* pages-repo/

          cd pages-repo

          # Configura usuario de Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Agrega cambios y pushea
          git add .
          git commit -m "Deploy Flutter Web" || echo "No hay cambios que commitear"
          git push
